### ISSUE TITLE
Support git based data sources

### ISSUE THREAD

**Issue by BrokenStandards** [Onemind-Services-LLC/netbox-metatype-importer#22] opened 2023-06-30 05:09 UTC
### NetBox version

v3.5.1

### Feature type

Add a function

### Proposed functionality

Enable use of git repos as a data source. This would compliment or replace the GitHub GraphQL data source.

### Use case

This would make us less reliant on GitHub as a platform. Add resiliency by removing total reliance on a single data source provider. And remove the requirement of setting up a personal access token. And remove the need of potentially creating service accounts just for access tokens.

While APIs are good and all, I'd rather cache the latest version locally or in the database through git than maintain access tokens unnecessarily

### External dependencies

GitPython

**Comment by abhi1693** [comment] 2023-07-17 14:59
Rather than reinventing the wheel, we can rely on NetBox data sources to provide this integration. Although, we will need to figure out how this transition happens.

**Comment by abhi1693** [comment] 2024-02-07 17:00
Duplicate of #21

**Closed by abhi1693** 2024-02-07 17:00 UTC
Labels: type: feature
